---
title: "Time Series Notes"
output: html_document
date: "2022-11-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Stationary Models



Autoregressive (AR) models base future predictions on previous values of the data (regress data against itself)

Moving Average (MA) models base future predictions on how wrong you were in your past predictions (previous forecast error)



## Steps in a time series analysis

1. Plot the data and the ACF/PACF
2. Decide if the data look stationary or not. If not, perform a suitable transformation (log, Box-Cox) and return to 1
3. Guess at a suitable p and q for an ARMA(p, q) model 
4. Fit the model
5. Try a few models around it by increasing/decreasing p and q and checking the AIC (or others)
6. Check the residuals
7. Forecast into the future



## Autoregressive (AR) Models

AR(p) Process:
    - There will be exponential decay in the ACF
    - There will be p sticking out ('significant') lags in the PACF
    - can use ACF and PACF to identify p from AR(p) - order of AR model
    - with AR(1) model, ACF shows exponential decay, while PACF only has large value for lag 1 and smaller values elsewhere
    
    

AR models are stationary
    - constant mean, variance and autocorrelation
    
- If a time series isn't stationary we might:
    - stabilise the mean by removing the trend or seasonality (by e.g. using linear regression)
        - difference or seasonally difference the time series (difference between each lag)
    - stabilise the variance by performing a transformation such as log or Box-Cox
    - fit a more advanced non-stationary model
    


Arima function in forecast package fits AR models

    - AR(1) model of data y
    - Arima(y, order = c(1, 0, 0))
    




## Moving Average (MA) models


MA models
    - exponential decay in PACF
    - sticking out lags in ACF




Arima function in forecast package fits MA models

    - MA(1) model of data y
    - Arima(y, order = c(0, 0, 1))





## ARMA models (Autoregressive Moving Average)

can combine AR and MA models - combine effects of previous lag and previous forecast error

ARMA(p,q) 
    - p = number of AR terms
    - q = number of MA terms







## ARIMA Models (Autoregressive Integrated Moving Average)

good for short-term forecasting

### combines ARMA with random walk

random walk - autoregressive model with beta=1

differences between t and t-1 are random noise


### differencing helps to remove trends

    - if y(t) = y(t-1) + b, 
    - t - t-1 = b
    - this removes the linear trend from the data and makes the values hover around b
    - differencing can also help to remove non-linear trends
    - differencing twice removes quadratic trends




## Forecast Plot

plot(forecast(modelname,h=(number of time steps into future)))
